### ISSUE TITLE
Selecting button style in SteppedForm (once ported)

### ISSUE THREAD

**Issue by luckylwk** [luckylwk/hoppin-design-system#10]
Added the following first step for the `onboard` @jonashaefele:

```
{
    slug: 'hello',
    title: 'Hello!',
    type: 'md',
    actions: [
      // { label: 'I want to learn more', navigate: 'next' },
      { label: 'I want to learn more', navigate: 'goto', slide: 'overview' },
      { label: 'Get started', navigate: 'goto', slide: 'name' }
    ],
    lede: `Lipsum`,
    body: `Lipsum`,
  },
```

 and then realized we can't define styling for the `navigate: 'goto'` buttons. It will by default become primary when using `navigate: 'next'`. Something to implement when moving the `SteppedForm` over to HDS

**Comment by jonashaefele** [comment]
just add `variant: 'primary'` or `variant: 'subtle` to the button. It'll forward the variant key from  the action object to the button.
