### ISSUE TITLE
Chat font not working

### ISSUE THREAD

**Issue by luckylwk** [luckylwk/hoppin-design-system#15]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/6073340/69964566-afa0c400-14e0-11ea-9e4e-f95e03aa40e5.png">

Can you have a look at this Jonas? I am working on the [feat-scheduler-errors-auth](https://github.com/luckylwk/hoppin-express-react-app/tree/luuk/feat-scheduler-errors-auth) branch of the app

**Comment by jonashaefele** [comment]
can't get that branch running 

```./src/bookingApp/pages/View/View.jsx
Module not found: Can't resolve 'react-intercom' in '/Users/jonas/dev/sites/hoppin-express-react-app/app/src/bookingApp/pages/View'``` seems like dependencies are missing.
